const NOT_ASKED = 'LOADING_STATE/NOT_ASKED';
const LOADING = 'LOADING_STATE/LOADING';
const LOADED = 'LOADING_STATE/LOADED';
const FAILED = 'LOADING_STATE/FAILED';

const LOADING_STATE = {
  NOT_ASKED,
  LOADING,
  LOADED,
  FAILED,
};

export default LOADING_STATE;
